# Shell variables
# Generated by 'wal'
wallpaper='/home/aulia/.config/wpg/wallpapers/Kogasa_WP_25.png'

# Special
background='#090E1C'
foreground='#ebcbbe'
cursor='#ebcbbe'

# Colors
color0='#090E1C'
color1='#3A4462'
color2='#525365'
color3='#977679'
color4='#2951B5'
color5='#6A6F89'
color6='#A18C92'
color7='#ebcbbe'
color8='#a48e85'
color9='#3A4462'
color10='#525365'
color11='#977679'
color12='#2951B5'
color13='#6A6F89'
color14='#A18C92'
color15='#ebcbbe'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
