#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  1 2 3 4 5 6 7 8 9 0

## overlapping border

bspc config border_width         1
bspc config window_gap           8
for side in top right bottom left ; do
	bspc config $(side)_padding $BW
done

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# autostart program
feh --bg-fill "~/.Picture/Kogasa WP 25.png"
~/.config/polybar/launch.sh
